version: '3'

services:
 db:
  image: mysql:8.0
  container_name: db
  ports:
  - "3307:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=mysql
  - MYSQL_PASSWORD=mysql
  - MYSQL_DATABASE=shopping_cart
 web:
  build: .
  ports:
  - "3030:3030"
  volumes:
  - "/go/src/app"
  depends_on:
  - db
  links:
  - "db:database"

